# Generated by Django 4.2.3 on 2023-07-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vct_app', '0002_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
