# Generated by Django 4.2.3 on 2023-07-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='team_logo_url',
            field=models.TextField(default=''),
        ),
    ]
