# Generated by Django 4.2.3 on 2023-07-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_player_photo_url_team_team_logo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='team',
            new_name='team_id',
        ),
    ]
