# Generated by Django 4.2.3 on 2023-07-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_rename_team_player_team_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='team_id',
            new_name='team',
        ),
    ]
